id: P6FCF8B68
initial_creation_type: input
source_metadata:
  title: Dying and the Bardos
  language: es
  description: 'Lotsawa House presents the following texts as part of our Dying and
    Bardos Series:'
  volume:
    e4b1448f4ad9468b881eb9a60d64e76d:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Dying
    948ae9d33faa4a86aee3fdd2ff13c2e2:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Dying
    49f4c71e5aa84b8fb23340616b4569de:
      title: Advice for Hor Özer
      parent: Dying
    ceda65e535314b23ad2d39c9c912b8d8:
      title: Advice for a Dying Practitioner
      parent: Dying
    298c6e0b82cb4dd78bcd35480e86fc85:
      title: Aspiration at the Moment of Death
      parent: Dying
    9cc93277933842869cde3185c6254e43:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dying
    b478b6f73d65490c89c018372d07a23d:
      title: A Wondrous Instruction for the Moment of Death
      parent: Dying
    fbc615af6b2d44eeab40866dab03ec39:
      title: Meditation on Amitābha
      parent: Dying
    207d6ea3408c4f879fd6370512d1f3a5:
      title: The Root Verses on the Six Bardos
      parent: Bardos
    1191e4fb9b86479087df40e7c89421c0:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Bardos
    cfdec43fdd50446a9abbd78da1be9a7e:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardos
    3ded9dd9434b43359298ad61b079acca:
      title: A Brief Introduction to the Bardos
      parent: Bardos
    71db21433edd435893f3496c00addb52:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Prayers
    4e393ba1c5d64cb49f3faf050e264447:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Prayers
    c4e436d0d3bc468789443fcf5dce9974:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Prayers
    16b4b67d9c904f7096e602998c66b783:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
created_at: '2022-03-01T03:30:40.703495'
last_modified_at: '2022-03-01T03:30:40.703497'
